name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install VTune
        uses: ./
      - name: Perform collection
        run: |
          sudo sysctl kernel.yama.ptrace_scope=0
          vtune -collect hotspots -result-dir=/tmp/vtune-results sleep 1
