name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  env:
    name: Check environment changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Capture initial environment
        run: env > before.env
        shell: bash
      - name: Install VTune
        uses: ./
      - name: Capture environment again
        run: env > after.env
        shell: bash
      - name: Compare "before" and "after" environments
        run: git diff --no-index before.env after.env || echo "differences found"
        shell: bash
