name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Check VTune works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Perform collection
        run: vtune -collect hotspots -knob sampling-mode=hw -result-dir=/tmp/vtune-results sleep 1
