name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install VTune
        uses: ./
      - name: Perform collection
        run: vtune -collect hotspots -result-dir=/tmp/vtune-results sleep 1
